# Generated by Django 3.1.7 on 2021-03-12 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=50)),
                ('song_file', models.FileField(upload_to='song/')),
                ('lyric_file', models.FileField(upload_to='lyric/')),
                ('image_file', models.ImageField(upload_to='image/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('title', 'singer', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyric_emotions', jsonfield.fields.JSONField(default=dict)),
                ('music_emotions', jsonfield.fields.JSONField(default=dict)),
                ('features', jsonfield.fields.JSONField(default=dict)),
                ('length', models.FloatField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewzicQ.song')),
            ],
        ),
    ]
